rmarkdown::render_site()
system("mv index.html gh-pages/")
system("mv eng.html gh-pages/")
system("mv rus.html gh-pages/")
system("cp footer.html gh-pages/")
system("cp _navbar.html gh-pages/")
# browseURL("index.html")
