---
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 6
---

</br>
</br>

## Conference

[Documentation, Standardization and Teaching of Endangered Languages in Northern Eurasia](http://langdoc.github.io/RIGNE2016/eng.html)

International scientific conference organized within the framework of the Regional Interest Group «Northern Eurasia» of the [Foundation for Endangered Languages (FEL)](http://www.ogmios.org/)


## Date

Murmansk, 25 November 2016


## Venue

[Murmansk Arctic State University](http://www.mspu.edu.ru), Murmansk, Russia


## Organizers

* Olga Ivanisheva, Saami Laboratory, Murmansk Arctic State University, Russia;
* Tjeerd de Graaf, Centre for Russian Studies, Groningen University and Fryske Academy, The Netherlands;
* Michael Rießler, Freiburg Research Group in Saami Studies, University of Freiburg, Germany


## Program committee

* Rogier Blokland, Department of Modern Languages (Finno-Ugric Languages), Uppsala University, Sweden;
* Alexandra Ershtadt, Saami Laboratory, Murmansk Arctic State University, Russia
* Marina Fedina, The Finno Ugric Laboratory for Support of the Electronic Representation of Regional Languages, Komi Republican Academy of State Civil Service and Administration, Russia;
* Andrey Filchenko, Department of Siberian Indigenous Languages of Tomsk State Pedagogical University, Russia;
* Reetta Toivanen, The Erik Castrén Institute of International Law and Human Rights, University of Helsinki, Finland


## Description

The [Foundation for Endangered Languages](http://www.ogmios.org/) exists to support, enable and assist the documentation, protection and promotion of endangered languages worldwide. One of the possibilities to accomplish this is to bring specialists together in a Regional Interest Group with representatives of certain endangered languages communities in a specific area of the world. The aim of the conference «RIGNE2016» in Murmansk is to initiate such a group specifically for Northern Eurasia. This group will be devoted to the study of and work with the endangered language communities in the arctic and subarctic regions between Fennoscandia and the Pacific Rim. At present the numerous and linguistically diverse indigenous languages in this area are highly vulnerable and may even face extinction if no effective measures are taken soon to ensure their better documentation, preservation and revitalization. 

Language documentation, language planning and language teaching are different endeavors belonging the separate subfields of applied linguistics. In the case of endangered indigenous languages, however, there is considerable overlap often as a result of the scarce material and personal resources for carrying out research, which is most typically bundled in relatively few projects, academic institutions or scientific networks. On the other hand, consistent collaboration across these fields of research has already produced valuable synergy effects resulting in methodological and theoretical advances in each single field. 

The conference focuses on the applied character of research on and for indigenous languages. We invite papers presenting topics on endangered language documentation, preservation and revitalization, in particular in the northern Eurasian area. Papers comparing the experience of local researchers in collaboration with specialists in the fields of language documentation, language planning and language teaching are especially welcome. 

The symposium is organized as a result of collaboration between academic institutions based in Russia and the Netherlands: specifically the [Murmansk Arctic State University](http://www.mspu.edu.ru) and the [Mercator Research Centre of the Fryske Akademy](http://www.mercator-research.eu/), the Department of Frisian Language and Culture and the Centre for Russian Studies of Groningen University. In this way further international relations between Murmansk and Groningen can hopefully be established in the future and the event can thus also contribute to the official city partnership between [Murmansk and Groningen](http://www.groningenmoermansk.nl/).


## Programme

The conference coincides with the Film & TV Festival «[Northern Character](http://northchar.ru/festival_/)» taking place from 24-26 November 2016 in Murmansk. Participants are invited to a presentation of a documentary film on the evening before the conference. After the conference, we will organize an excursion to Lovozero.


### 24 November 2016

Pre-conference programme

Film documentary (place and time t.b.a)


### 25 November 2016

Conference day

#### 09:00 Opening speeches

Murmansk Arctic State University, City-twinning Murmansk-Groningen and Fryske Academy

#### 09:30 Plenary speech

Marina Lublinskaya and Maria Dugina (St. Petersburg)

Teaching of Northern Indigenous Languages at Gercen University

Chair: Olga Ivanischeva

#### 10:30–11:00 Break

#### 11:00–12:30 Session

Chair: Michael Rießler

##### 11:00 Olga Kazakevich (Moscow)

Evenki local dialects of Irkutsk region: current linguistic situation and future prospectives

##### 11:30 Varvara Belolyubskaya, Antonina Vinokurova, Sargylana Vinokurova, N. Nikolaeva (Yakutsk)

Лексика, отражающая охотничью культуру эвенов и эвенков

##### 12:00 Evgeniya Zhivotova (Leipzig)

Роль документации быстринского говора эвенского языка на примере заимствований служебных слов в ситуации языкового контакта

#### 12:30–14:00 Lunch

#### 14:00–15:30 Session

Chair: Tjeerd de Graaf

##### 14:00 Tatyana Agranat (Moscow)

Документирование идиома печорских сето

##### 14:30 Alexandre Arkhipov (Hamburg)

The INEL project: Research infrastructure for Northern Eurasian languages

##### 15:00 Reetta Toivanen (Helsinki)

Research on and for endangered languages and its role for revitalization

#### 15:30–16:00 Break

#### 16:00–17:00 Session

Chair: Reetta Toivanen

##### 16:00 Tim Feist (Gilford)

Data visualisations as a pedagogical tool for Skolt Saami

##### 16:30 Olga Ivanischeva (Murmansk)

Тематические группы «Растения», «Рыбы», «Рельеф» и «Вода» в кильдинском саамском языке

#### 17:00–18:00 General discussion and foundation meeting of the Regional Interest Group «Northern Eurasia»

Chair: Tjeerd de Graaf and Michael Rießler

#### 19:30 Dinner

(place and time t.b.a)

### 26 November 2016

Excursion to Lovozero (place and time t.b.a)


## Contact

* Alexandra Ershtadt [alexandra.ershtadt@gmail.com]
* Michael Rießler [m.riessler@gmail.com]


