---
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 6
---

</br>
</br>

## Конференция

[Документация, стандартизация и преподавание исчезающих языков Северной Евразии](http://langdoc.github.io/RIGNE2016/rus.html)

Международная научно-практическая конференция проводится в рамках работы региональной группы «Северная Евразия» Фонда (документации) исчезающих языков (FEL)


## Сроки проведения

25–26 ноября 2016 г.


## Место проведения

[Мурманский арктический государственный университет](http://www.mspu.edu.ru), г. Мурманск, Россия 


## Контакты

* Александра Эрштадт [alexandra.ershtadt@gmail.com]
* Михаэль Рисслер [m.riessler@gmail.com]


## Программа

Конференция проходит одновременно с международным фестивалем документальных фильмов и телевизионных программ с участием северных стран «[Северный характер](http://northchar.ru/festival_/)», который проводится в г. Мурманске в период с 24 по 26 ноября 2016 г. Участники конференции приглашаются на презентацию документального фильма вечером дня, предшествующего дню начала работы конференции. 

После завершения конференции состоится экскурсия в с. Ловозеро. 

### 24 ноября 2016 г.

Культурная программа

Просмотр документального фильма (место и время будут уточнены) 


### 25 ноября 2016 г. 

Начало работы конференции

#### 09:00 Вступительное слово

Мурманский арктический государственный университет, города-побратимы Мурманск и Гронинген и Фризская академия 


#### 09:30 Пленарное выступление

Люблинская М.Д., к.ф.н, Дугина М., Российский государственный педагогический университет им. А.И. Герцена (г. Санкт-Петербург)

Teaching of Northern Indigenous Languages at Gercen University

Руководитель: Иванищева О.Н., д.ф.н., профессор, Мурманский арктический государственный университет (г. Мурманск) 

#### 10:30–11:00 Перерыв

#### 11:00–12:30 Секция

Руководитель: Рисслер М., д.ф.н., Университет Алберта Лудвига (г. Фрайбург, Германия)

##### 11:00 Казакевич О.А., к.ф.н., зав. лаб. (лаборатория автоматизированных лексикографических систем) НИВЦ МГУ им. М.В. Ломоносова, Институт языкознания РАН (г. Москва)   

Evenki local dialects of Irkutsk region: current linguistic situation and future prospectives

##### 11:30 Белолюбская В.Г., к.ф.н., Винокурова А.А., к.ф.н., Винокурова С.Д., Николаева Н.П., Северо-восточный федеральный университет имени М.К. Аммосова (г. Якутск)

Лексика, отражающая охотничью культуру эвенов и эвенков

##### 12:00 Животова Е., MA, Лейпцигский университет (г. Лейпциг, Германия) 

Роль документации быстринского говора эвенского языка на примере заимствований служебных слов в ситуации языкового контакта

#### 12:30–13:30 Обед

#### 13:30–15:00 Секция

Руководитель: Тьерд де Граф, PhD, Фризская академия (г. Леуварден, Нидерланды)

##### 13:30 Иванищева О.Н., Мурманский арктический государственный университет (г. Мурманск) 

Тематические группы «Растения», «Рыбы», «Рельеф» и «Вода» в кильдинском саамском языке

##### 14:00 Феист Т., PhD, Университет Суррея (г. Гилдфорд, Англия) 

Data visualisations as a pedagogical tool

##### 14:30 Норманская Ю.В., д.ф.н., профессор, Институт языкознания РАН (г. Москва) 

Язык первого кильдинского Евангелия в сравнении с современными кильдинскими говорами

#### 15:00–15:30 Перерыв

#### 15:30–17:00 Секция

Руководитель: Эрштадт А.М., к.ф.н., Мурманский арктический государственный университет (г. Мурманск)

##### 15:30 Агранат Т.Б., д.ф.н., профессор, Институт языкознания РАН (г. Москва) 

Документирование идиома печорских сето

##### 16:00 Каксин А.Д, д.ф.н., профессор  Хакасский государственный университет им. Н.Ф. Катанова, Институт гуманитарных исследований и саяно-алтайской тюркологии (г. Абакан) 

Проблемы перевода общественно-политической лексики на языки малочисленных народов Российской Федерации (на примере хантыйского языка)

##### 16:30 Архипов А.В., к.ф.н., Гамбургский университет (г. Гамбург, Германия) 

The INEL project: Research infrastructure for Northern Eurasian languages

#### 17:00–18:00 Общее обсуждение и заседание региональной группы «Северная Евразия» фонда (документации) исчезающих языков (FEL) 

Руководитель: Тьерд де Граф 

#### 19:30 Ужин


### 26 ноября 2016 г.

Культурная программа

Экскурсия в с. Ловозеро (время и место будут уточнены) 
