---
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 6
---

</br>
</br>

## Conference

[Documentation, Standardization and Teaching of Endangered Languages in Northern Eurasia](http://langdoc.github.io/RIGNE2016/eng.html)

International scientific conference organized within the framework of the Regional Interest Group «Northern Eurasia» of the Foundation for Endangered Languages (FEL)


## Date

Murmansk, 25–26 November 2016


## Venue

[Murmansk Arctic State University](http://www.mspu.edu.ru), Murmansk, Russia


## Contact

* Alexandra Ershtadt [alexandra.ershtadt@gmail.com]
* Michael Rießler [m.riessler@gmail.com]


## Programme

The conference coincides with the Film & TV Festival «[Northern Character](http://northchar.ru/festival_/)» taking place from 24-26 November 2016 in Murmansk. Participants are invited to a presentation of a documentary film on the evening before the conference. After the conference, we will organize an excursion to Lovozero.


### 24 November 2016

Pre-conference programme

Film documentary (place and time t.b.a)


### 25 November 2016

Conference day

#### 09:00 Opening speeches

Murmansk Arctic State University, City-twinning Murmansk-Groningen and Fryske Academy

#### 09:30 Plenary speech

Marina Lublinskaya and Maria Dugina (St. Petersburg)

Teaching of Northern Indigenous Languages at Gercen University

Chair: Olga Ivanischeva

#### 10:30–11:00 Break

#### 11:00–13:00 Session

Chair: Michael Rießler

##### 11:00 Olga Kazakevich (Moscow)

Evenki local dialects of Irkutsk region: current linguistic situation and future prospectives

##### 11:30 Varvara Belolyubskaya, Antonina Vinokurova, Sargylana Vinokurova, N. Nikolaeva (Yakutsk)

Лексика, отражающая охотничью культуру эвенов и эвенков

##### 12:00 Evgeniya Zhivotova (Leipzig)

Роль документации быстринского говора эвенского языка на примере заимствований служебных слов в ситуации языкового контакта

#### 12:30–13:30 Lunch

#### 13:30–15:00 Session

Chair: Tjeerd de Graaf

##### 13:30 Olga Ivanischeva (Murmansk)

Тематические группы «Растения», «Рыбы», «Рельеф» и «Вода» в кильдинском саамском языке

##### 14:00 Tim Feist (Gilford)

Data visualisations as a pedagogical tool

##### 14:30 Julia Normanskaya (Moscow)

Язык первого кильдинского Евангелия в сравнении с современными кильдинскими говорами

#### 15:00–15:30 Break

#### 15:30–17:00 Session

Chair: Alexandra Ershtadt

##### 15:30 Tatyana Agranat (Moscow)

Документирование идиома печорских сето

##### 16:30 Andrey Kaksin (Abakan)

Проблемы перевода общественно-политической лексики на языки малочисленных народов Российской Федерации (на примере хантыйского языка)

##### 16:30 Alexandre Arkhipov (Hamburg)

The INEL project: Research infrastructure for Northern Eurasian languages

#### 17:00–18:00 General discussion and foundation meeting of the Regional Interest Group «Northern Eurasia»

Chair: Tjeerd de Graaf

#### 19:30 Dinner


### 26 November 2016

Excursion to Lovozero (place and time t.b.a)
