---
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 6
---

</br>
</br>

## Конференция

[Документация, стандартизация и преподавание исчезающих языков Северной Евразии](http://langdoc.github.io/RIGNE2016/rus.html)

Международная научно-практическая конференция проводится в рамках работы региональной группы «Северная Евразия» [Фонда (документации) исчезающих языков (FEL)](http://www.ogmios.org/)


## Сроки проведения

25–26 ноября 2016 г.


## Место проведения

[Мурманский арктический государственный университет](http://www.mspu.edu.ru), г. Мурманск, Россия 


## Приглашенный докладчик

Люблинская М.Д., к.ф.н, Дугина М., Российский государственный педагогический университет им. А.И. Герцена (г. Санкт-Петербург)


## Организаторы

* Ольга Иванищева, д.ф.н, профессор, Лаборатория саамского языка, Мурманский арктический государственный университет, Россия; 
* Тьерд де Грааф, PhD, Центр российских исследований, университет г. Гронинген и Фризская академия, Голландия;
* Михаэль Рисслер, PhD, д.ф.н, Лаборатория по изучению саамских языков, университет г. Фрайбург, Германия. 


## Организационный совет

* Рохир Блокланд, PhD, профессор, Финно-угорское отделение, университет г. Уппсала, Швеция; 
* Александра Эрштадт, к.ф.н, Лаборатория саамского языка, Мурманский арктический государственный университет, Россия;
* Марина Федина, к.ф.н, Межрегиональная лаборатория информационной поддержки функционирования финно-угорских языков, Коми республиканская академия государственной службы и управления, Россия;
* Андрей Фильченко, PhD, Кафедра языков народов Сибири, Томский государственный педагогический университет, Россия;
* Реетта Тойванен, PhD, д.ф.н, Институт международного права и прав человека им. Эрика. Кастрена, университет г. Хельсинки, Финляндия. 


## Описание

Целью работы [Фонда (документации) исчезающих языков](http://www.ogmios.org/) является оказание поддержки и содействия работе по документации, сохранению и развитию исчезающих языков во всем мире. Одним из путей достижения этой цели является совместная работа специалистов в региональных группах, включающих представителей сообществ носителей исчезающих языков определенной географической области. 

Целью проведения международной научно-практической конференции «RIGNE2016» в г. Мурманск является организация такой группы для Северной Евразии с целью изучения и работы с исчезающими языками арктических и субарктических регионов, расположенных между Фенноскандией и Тихоокеанским кольцом. В настоящее время множество языков коренных народов данного региона находятся в крайне уязвимом положении и могут исчезнуть, если в кратчайшие сроки не будут приняты эффективные меры по их документации, сохранению и ревитализации. 

Документация языков, языковое планирование и преподавание языков являются областями различных направлений прикладной лингвистики, однако в случае исчезающих языков ввиду недостаточности материалов и ресурсов для проведения исследований они обычно тесно переплетаются в работе немногочисленных проектов, исследовательских организаций и научных объединений. С другой стороны, постоянное взаимодействие на стыке этих областей уже имеет полезный взаимоусиливающий эффект, обеспечивающий методологические и теоретические преимущества для каждой из этих областей в отдельности. 

Центром внимания научно-практической конференции станут прикладные исследования языков коренных народов. К участию приглашаются особенно исследователи, занимающиеся документацией исчезающих языков Северной Евразии, их сохранением и ревитализацией. Особый интерес будет представлять опыт сотрудничества местных исследователей со специалистами по документации языков, языковому планированию и преподаванию языков. 

Научно-практическая конференция проводится в результате сотрудничества научно-образовательных учреждений России и Голландии, а именно Мурманского арктического государственного университета и Центра исследований Меркатора при Фризской академии, отделения фризского языка и культуры и Центра российских исследований университета г. Гронингена. Проведение конференции позволит установить новые связи и укрепить существующие побратимские отношения между городами Мурманск и Гронинген. 


## Программа

Конференция проходит одновременно с международным фестивалем документальных фильмов и телевизионных программ с участием северных стран «[Северный характер](http://northchar.ru/festival_/)», который проводится в г. Мурманске в период с 24 по 26 ноября 2016 г. Участники конференции приглашаются на презентацию документального фильма вечером дня, предшествующего дню начала работы конференции. После завершения конференции состоится экскурсия в с. Ловозеро. 

### 24 ноября 2016 г.

Культурная программа

Просмотр документального фильма (место и время будут уточнены) 


### 25 ноября 2016 г. 

Начало работы конференции

#### 09:00 Вступительное слово

Мурманский арктический государственный университет, города-побратимы Мурманск и Гронинген и Фризская академия 


#### 09:30 Пленарное выступление

Люблинская М.Д., к.ф.н, Дугина М., Российский государственный педагогический университет им. А.И. Герцена (г. Санкт-Петербург)

Teaching of Northern Indigenous Languages at Gercen University

Председатель: Иванищева О.Н., д.ф.н., профессор, Мурманский арктический государственный университет (г. Мурманск) 

#### 10:30–11:00 Перерыв

#### 11:00–13:00 Секция

Председатель: Рисслер М., д.ф.н., Университет Алберта Лудвига (г. Фрайбург, Германия)

##### 11:00 Казакевич О.А., к.ф.н., Институт языкознания РАН (г. Москва) 

Evenki local dialects of Irkutsk region: current linguistic situation and future prospectives

##### 11:30 Белолюбская В.Г., к.ф.н., Винокурова А.А., к.ф.н., Винокурова С.Д., Николаева Н.П., Северо-восточный федеральный университет имени М.К. Аммосова (г. Якутск)

Лексика, отражающая охотничью культуру эвенов и эвенков

##### 12:00 Животова Е, MA, Лейпцигский университет (г. Лейпциг, Германия) 

Роль документации быстринского говора эвенского языка на примере заимствований служебных слов в ситуации языкового контакта

#### 12:30–13:30 Обед

#### 13:30–15:00 Секция

Председатель: Тьерд де Граф, PhD, Фризская академия (г. Леуварден, Нидерланды)

##### 13:30 Иванищева О.Н., Мурманский арктический государственный университет (г. Мурманск) 

Тематические группы «Растения», «Рыбы», «Рельеф» и «Вода» в кильдинском саамском языке

##### 14:00 Феист Т., PhD, Университет Суррея (г. Гилфорд, Англия) 

Data visualisations as a pedagogical tool

##### 14:30 Норманская Ю.В., д.ф.н., профессор, Институт языкознания РАН (г. Москва) 

Язык первого кильдинского Евангелия в сравнении с современными кильдинскими говорами

#### 15:00–15:30 Перерыв

#### 15:30–17:00 Секция

Председатель: Эрштадт А.М., к.ф.н., Мурманский арктический государственный университет (г. Мурманск)

##### 15:30 Агранат Т.Б., д.ф.н., профессор, Институт языкознания РАН (г. Москва) 

Документирование идиома печорских сето

##### 16:30 Каксин А.Д, д.ф.н., профессор  Хакасский государственный университет им. Н.Ф. Катанова, Институт гуманитарных исследований и саяно-алтайской тюркологии (г. Абакан) 

Проблемы перевода общественно-политической лексики на языки малочисленных народов Российской Федерации (на примере хантыйского языка)

##### 16:30 Архипов А.В., к.ф.н., Гамбургский университет (г. Гамбург, Германия) 

The INEL project: Research infrastructure for Northern Eurasian languages

#### 17:00–18:00 Общее обсуждение и заседание региональной группы «Северная Евразия» фонда (документации) исчезающих языков (FEL) 

Председатель: Тьерд де Граф 

#### 19:30 Ужин


### 26 ноября 2016 г.

Культурная программа

Экскурсия в с. Ловозеро (время и место будут уточнены) 


## Контакты

* Александра Эрштадт [alexandra.ershtadt@gmail.com]
* Михаэль Рисслер [m.riessler@gmail.com]
